#ubuntu@ip:~/my_website_onnx2$ docker images
#REPOSITORY           TAG       IMAGE ID       CREATED              SIZE
#sherpa_onnx_server   latest    e7010873bbd6   About a minute ago   3.19GB

FROM python:3
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        g++ \
        make \
        automake \
        autoconf \
        bzip2 \
        unzip \
        wget \
        sox \
        libtool \
        git \
        subversion \
        zlib1g-dev \
        gfortran \
        ca-certificates \
        patch \
        ffmpeg \
	screen \
	nano \
        lsof \
        valgrind \
	libssl-dev \
	vim \
	curl \
        pip

RUN pip install websockets

# cmake looks like sherpa-onnx needs this
RUN wget -P /opt https://cmake.org/files/v3.18/cmake-3.18.0.tar.gz && \
    cd /opt && \
    tar -zxvf cmake-3.18.0.tar.gz && \
    cd cmake-3.18.0 && \
    ./bootstrap && \
    make && \
    make install && \
    rm -rf cmake-3.18.0.tar.gz && \
    find /opt/cmake-3.18.0 -type f \( -name "*.o" -o -name "*.la" -o -name "*.a" \) -exec rm {} \; && \
    cd -


RUN git clone https://github.com/k2-fsa/sherpa-onnx /workspace/sherpa-onnx
RUN cd /workspace/sherpa-onnx && \
      python3 setup.py install --verbose && \
      cd -

	
RUN mkdir /workspace/k2_models
RUN apt update -y
RUN apt install git-lfs -y
RUN git lfs install

# This model is converted from
#https://huggingface.co/marcoyang/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04
#which supports only English as it is trained on the LibriSpeech and GigaSpeech corpus.
RUN git clone https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-21 /workspace/k2_models/sherpa-onnx-streaming-zipformer-en-2023-06-21
RUN cd /workspace/k2_models/sherpa-onnx-streaming-zipformer-en-2023-06-21 && \
       git lfs pull --include "*.onnx" && \
       cd -


RUN mkdir /workspace/my_website
COPY . /workspace/my_website

ENV PYTHONPATH /workspace/my_website:$PYTHONPATH

WORKDIR /workspace/my_website
EXPOSE 6006
EXPOSE 6008
ENTRYPOINT ./run_onnx_libri_giga.sh 
